apiVersion: elasti.truefoundry.com/v1alpha1
kind: ElastiService
metadata:
  labels:
    app.kubernetes.io/name: elasti-operator
    app.kubernetes.io/managed-by: kustomize
  name: httpbin
spec:
  service: httpbin
  minTargetReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployments
    name: httpbin