---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: target-statefulset
---
apiVersion: v1
kind: Service
metadata:
  name: target-statefulset
spec:
  type: ClusterIP
  selector:
    app: target-statefulset
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: target-statefulset
spec:
  serviceName: target-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: target-statefulset
  template:
    metadata:
      labels:
        app: target-statefulset
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        sidecar.istio.io/statsInclusionPrefixes: "cluster,listener,server,http,tcp"
    spec:
      serviceAccountName: target-statefulset
      containers:
        - name: target-statefulset
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: target-statefulset-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /httpbin(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: target-statefulset
                port:
                  number: 80
