apiVersion: elasti.truefoundry.com/v1alpha1
kind: ElastiService
metadata:
  labels:
    app.kubernetes.io/name: elasti-operator
    app.kubernetes.io/managed-by: kustomize
  name: ishaan-elasti-test
  namespace: ishaan-ws
spec:
  minTargetReplicas: 2
  service: ishaan-elasti-test
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: rollouts
    name: ishaan-elasti-test

