apiVersion: elasti.truefoundry.com/v1alpha1
kind: ElastiService
metadata:
  name: httpbin
  namespace: target
spec:
  service: httpbin
  minTargetReplicas: 1
  cooldownPeriod: 1000
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployments
    name: httpbin
  triggers:
    - metadata:
        query: round(sum(rate(envoy_http_downstream_rq_total{container="istio-proxy"}[1m])),0.001) or vector(0)
        serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
        threshold: "0.01"
      type: prometheus
