apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app.kubernetes.io/name: elasti-resolver
  name: elasti-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasti-resolver 
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8012"
        prometheus.io/path: "/metrics"
      labels:
        app: elasti-resolver 
    spec:
      containers:
      - name: proxy
        image: localhost:5001/elasti-resolver:v1alpha1
        imagePullPolicy: Always
        env:
        - name: MAX_IDLE_PROXY_CONNS
          value: "100"
        - name: MAX_IDLE_PROXY_CONNS_PER_HOST
          value: "500"
        - name: REQ_TIMEOUT
          value: "120"       
        - name: TRAFFIC_RE_ENABLE_DURATION
          value: "5"
        - name: OPERATOR_RETRY_DURATION
          value: "10"
        - name: HEADER_FOR_HOST
          value: X-Envoy-Decorator-Operation
        - name: QUEUE_SIZE
          value: "50000"
        - name: QUEUE_RETRY_DURATION
          value: "3"       
        - name: MAX_QUEUE_CONCURRENCY
          value: "100"
        - name: INITIAL_CAPACITY
          value: "500"
        ports:
        - containerPort: 8012
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"  
          limits:
            memory: "1Gi"
            cpu: "750m"  

