elastiController:
  manager:
    image:
      repository: localhost:5000/elasti-operator
      tag: v1alpha1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
elastiResolver:
  proxy:
    image:
      repository: localhost:5000/elasti-resolver
      tag: v1alpha1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
