global:
  kubernetesClusterDomain: cluster.local
  nameOverride: ""
  fullnameOverride: ""
  enableMonitroing: true
elastiController:
  manager:
    args:
    - --leader-elect
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: localhost:5000/elasti-operator
      tag: v1alpha1
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  metricsService:
    port: 8080
    type: ClusterIP
  service:
    port: 8013
    type: ClusterIP

elastiResolver:
  proxy:
    env:
      headerForHost: X-Envoy-Decorator-Operation
      initialCapacity: "500"
      maxIdleProxyConns: "100"
      maxIdleProxyConnsPerHost: "500"
      maxQueueConcurrency: "100"
      operatorRetryDuration: "10"
      queueRetryDuration: "3"
      queueSize: "50000"
      reqTimeout: "120"
      trafficReEnableDuration: "5"
    image:
      repository: localhost:5000/elasti-resolver
      tag: v1alpha1
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 500Mi
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
  service:
    port: 8012
    type: LoadBalancer
