name: Push image to JFROG Public

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  build-operator:
    name: Build and Push Operator Docker Images
    uses: truefoundry/workflows/.github/workflows/build.yml@v0.2.4
    with:
      image_tag: ${{ github.sha }}
      image_artifact_name: 'elasti-operator'
      dockerfile_path: 'operator/Dockerfile'
      depot_project_id: ${{ vars.DEPOT_PROJECT_ID }}
      artifactory_registry_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
      artifactory_repository_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}
    secrets:
      depot_token: ${{ secrets.DEPOT_API_KEY }}
      artifactory_username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
      artifactory_password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}

  build-resolver:
    name: Build and Push Resolver Docker Images
    uses: truefoundry/workflows/.github/workflows/build.yml@v0.2.4
    with:
      image_tag: ${{ github.sha }}
      image_artifact_name: 'elasti-resolver'
      dockerfile_path: 'resolver/Dockerfile'
      depot_project_id: ${{ vars.DEPOT_PROJECT_ID }}
      artifactory_registry_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
      artifactory_repository_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}
    secrets:
      depot_token: ${{ secrets.DEPOT_API_KEY }}
      artifactory_username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
      artifactory_password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}
