name: Push image to to JFROG Public

on:
  push:
    branches:
      - 'main'
      - 'update-build-workflow'

permissions:
  id-token: write
  contents: read

jobs:
  build-operator:
    name: Build and Push Operator Docker Images
    uses: truefoundry/workflows/.github/workflows/build.yml@update-build-workflow
    with:
      artifactory_registry: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
      image_tag: ${{ github.sha }}
      repository: 'operator'
      dockerfile_path: 'operator/Dockerfile'
    secrets:
      artifactory_username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
      artifactory_password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}

  build-resolver:
    name: Build and Push Resolver Docker Images
    uses: truefoundry/workflows/.github/workflows/build.yml@update-build-workflow
    with:
      artifactory_username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
      artifactory_password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}
      artifactory_registry: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
      image_tag: ${{ github.sha }}
      repository: 'resolver'
      dockerfile_path: 'resolver/Dockerfile'
