name: Push image to to JFROG Public

on:
  push:
    branches:
      - 'main'
      - 'update-build-workflow'

permissions:
  id-token: write
  contents: read

env:
  ARTIFACTORY_USERNAME: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}
  ARTIFACTORY_REGISTRY: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}

jobs:
  build-operator:
    name: Build and Push Operator Docker Images
    uses: truefoundry/workflows/.github/workflows/build.yml@update-build-workflow
    with:
      artifactory_username: ${{ env.ARTIFACTORY_USERNAME }}
      artifactory_password: ${{ env.ARTIFACTORY_PASSWORD }}
      artifactory_registry: ${{ env.ARTIFACTORY_REGISTRY }}
      image_tag: ${{ github.sha }}
      repository: 'operator'
      dockerfile_path: 'operator/Dockerfile'

  build-resolver:
    name: Build and Push Resolver Docker Images
    uses: truefoundry/workflows/.github/workflows/build.yml@update-build-workflow
    with:
      artifactory_username: ${{ env.ARTIFACTORY_USERNAME }}
      artifactory_password: ${{ env.ARTIFACTORY_PASSWORD }}
      artifactory_registry: ${{ env.ARTIFACTORY_REGISTRY }}
      image_tag: ${{ github.sha }}
      repository: 'resolver'
      dockerfile_path: 'resolver/Dockerfile'
