name: Push image to to JFROG Public

on:
  push:
    branches:
      - 'main'
      - feat/arm-build
    # paths:
    #   - 'operator/**'
    #   - 'resolver/**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push Docker Images
    strategy:
      matrix:
        include:
          - directory: operator
            repository: elasti-operator
          - directory: resolver
            repository: elasti-resolver
    uses: truefoundry/workflows/.github/workflows/build.yml@main
    with:
      directory: ${{ matrix.directory}}
      repository: ${{ matrix.repository}}
      internal: false
      private: false
    secrets: inherit
