name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'operator/**'
      - 'resolver/**'
      - 'pkg/**'
      - '*.go'
      - 'go.mod'
      - 'go.sum'
      - 'go.work'
      - 'go.work.sum'

permissions:
  contents: read

env:
  GO_VERSION: 1.26.5

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: operator
          - module: resolver
          - module: pkg
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: "0"
      - name: Setup go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Install dependencies
        run: go mod tidy
        working-directory: ${{ matrix.module }}
      - name: Run tests with coverage
        run: cd ${{ matrix.module }} && make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ matrix.module }}/cover.out
          flags: ${{ matrix.module }}
          name: ${{ matrix.module }}
          fail_ci_if_error: false
