name: Release Elasti Helm Chart

on:
  push:
    tags:
      - elasti-helm-v*
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
    
      - name: Add yq through apt
        run: |
            sudo apt update && sudo apt install wget -y && sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
            sudo chmod +x /usr/bin/yq


      - name: Helm registry login
        run: |
          helm registry login -u ${{ secrets.OCI_REGISTRY_USERNAME}} -p ${{ secrets.OCI_REGISTRY_PASSWORD }} quay.io
     
      - name: Helm push 
        run: |
            cd charts
            for CHART_DIR in $(ls -d */)
            do
                CHART_DIR=$(basename $CHART_DIR)
                echo "CHARTDIR: $CHART_DIR/Chart.yaml"
                # getting chart name and versions
                CHART_NAME=$(yq '.name' $CHART_DIR/Chart.yaml)
                CHART_VERSION=$(yq '.version' "$CHART_DIR"/Chart.yaml)
                
                # packaging chart
                helm dependency update $CHART_DIR
                helm package $CHART_DIR

                # pushing the helm charts
                echo "Pushing Chart: $CHART_NAME"
                echo "Version: $CHART_NAME-$CHART_VERSION.tgz"
                helm push $CHART_NAME-$CHART_VERSION.tgz oci://quay.io/truefoundrycharts
                echo "Successfully pushed chart: $CHART_NAME"
            done